### PR TITLE
IrWidgetAggregating: Cleanup and Bugfixes

### PR DESCRIPTION
**Pull request by mparthey**
Hello Bengt,

thanks a lot for your Arduino IR receiver and related software.

I built the hardware using a clone of the Pro Micro:
https://www.sparkfun.com/products/12640
a photodiode and this simple transistor amplifier:
http://rn-wissen.de/wiki/index.php?title=Datei:FotodiodenVerst.png

Then I did some review of the code in IrWidgetAggregating.cpp,
and this patch series is the result of my cleanup work. 
The first half of the patches are mostly cleanups,
while the second half fixes small bugs.

The new code works well for me when used with IrScrutinizer. 
However, it has not undergone any more rigorous analysis/testing
using a logic analyzer, debugger or disassembler.

Please let me know if you want anything changed or explained in more detail.

Michael Dreher @nospam2000
Would you like to help with code review and testing?

Regards,
Mirko

### CODE REVIEW

**Comment by bengtmartensson** [comment]
Hi Mirko,
thanx a bunch for this. Actually, IrWidget[Aggregating] are Michael's code, I have just reorganized it a bit and adapted it to the rest of the package. Frankly, I do not understand it more than superficially, and am not really happy with that. 

Your changes all look good at a first impression -- with one exception. What I do not like is that your new macros should be private, and not exported in a header file, as is presently the case. 

I would love to hear from Michael in this matter.  You intention is (as I have understood it), that the changes are _almost_ neutral for the behavior. I will test it shortly. 

Greetz,
Bengt

**Comment by nospam2000** [comment]
I will review the changes, but it will take some time. The code was speed optimized (the best I could get out without using asm) and not for readability or clarity.

Michael

**Comment by mparthey** [comment]
@nospam2000
Hello Michael,
have you found some time to review my changes yet?

Hello Bengt,
thanks for your preliminary review.  I agree that my macros should be made private.

Sorry for my late reply, my plan was to deal with all reviews at once,
but now decided to handle what's there.

I see that your master branch has advanced - do you want me to merge it into
mine and push my macro fix on top, or should I rebase my branch on top 
of master for a clean history?

Does the code work for you?

Describing my patchset as "_almost_ neutral in behaviour" sums it up nicely.
My primary goal was to understand the code, and perhaps to contribute something.
The patches sort of emerged from that.

Let me know if I can do anything to help you better understand Michael's code and my changes.
If you can read German, you might be already familiar with [Michael's article](https://www.mikrocontroller.net/articles/High-Speed_capture_mit_ATmega_Timer).

Regards
Mirko

**Comment by bengtmartensson** [comment]
The work I did in early May was essentially, cleanup, testing examples, and documentation, particular with Doxygen. The library is now in the official library library manager! These changes were, at least in principle, completely orthogonal to the PR, so merging that should not pose any real problems -- with or without rebasing. 

I still hope to hear from  @nospam2000 . Michael, would you give yourself a deadline, e.g. June 1st?

**Comment by bengtmartensson** [comment]
Mirko,
thanks again for your effort. I have reluctantly decided to decline you PR. Sorry.

Generally speaking, this PR adds nothing in functionality, nor fixes bugs, but claims to cleanup the code. The original code by now works, and is reasonably stable. I am generally hesitant to accept changes unless they really have a benefit. (Making the code more readable definitely counts)  Your changes leaves fairy cryptic code as fairly cryptic code.

For dead storage and the like, let's not forget that todays compiler optimizes away unnecessary code (like dead storage)- Still, e.g. dead storage might be bad, because it indicates a misunderstanding on the side of the author. It may also "look uncool" for some static code analyzers, like findbugs for Java. 

Specific comments to the commits:
1. I do not think the macros are an improvement. They are used as abbreviations, not really to reduce the abstraction level. The resulting code is (at least) as cryptic as the original one, possibly even harder to understand, because of an extra level of indirection. Rejected.
2. Yes, this is dead storage. 
3. Agreed, your code is better and clearer than the original one. 
8. Reject, because "This changes the semantics of endingTimeout".

If there is a real misbehavior in the code that you changes fixes, please let me know.

**Comment by mparthey** [comment]
Bengt,

thanks for your review. I can understand and agree with your decision.
Any cleanup work should not just improve the code a little bit,
but actually result in good code.
However, I won't pursue this any further for now.

Mirko

**Pull request closed without merging**
